#The time between text change on signs in seconds
time-between-change: 60

#Messages Section
messages:
    1:
        line-1: abc #Line 1 of sign
        line-2: def #Line 2 of sign
        line-3: ghi #Line 3 of sign
        line-4: jkl #Line 4 of sign
        interact-message: Hi #Message sent when sign is right clicked
    2:
        line-1: mno
        line-2: pqr
        line-3: stu
        line-4: vwx
        interact-message: Hello